#pragma once 


#ifndef __FILESYSTEM_NAMESPACE_BEGIN
#define __FILESYSTEM_NAMESPACE_BEGIN namespace filesystem {
#endif // __FILESYSTEM_NAMESPACE_BEGIN

#ifndef __FILESYSTEM_NAMESPACE_END
#define __FILESYSTEM_NAMESPACE_END }
#endif // __FILESYSTEM_NAMESPACE_END


#ifndef __FILESYSTEM_IP_NAMESPACE_BEGIN
#define __FILESYSTEM_IP_NAMESPACE_BEGIN namespace filesystem { namespace ip {
#endif // __FILESYSTEM_IP_NAMESPACE_BEGIN

#ifndef __FILESYSTEM_IP_NAMESPACE_END
#define __FILESYSTEM_IP_NAMESPACE_END }}
#endif // __FILESYSTEM_IP_NAMESPACE_END



#ifndef __FILESYSTEM_OPTIONS_NAMESPACE_BEGIN
#define __FILESYSTEM_OPTIONS_NAMESPACE_BEGIN namespace filesystem { namespace options {
#endif // __FILESYSTEM_OPTIONS_NAMESPACE_BEGIN

#ifndef __FILESYSTEM_OPTIONS_NAMESPACE_END
#define __FILESYSTEM_OPTIONS_NAMESPACE_END }}
#endif // __FILESYSTEM_OPTIONS_NAMESPACE_END



#ifndef __FILESYSTEM_OPTIONS_CONCEPTS_NAMESPACE_BEGIN
#define __FILESYSTEM_OPTIONS_CONCEPTS_NAMESPACE_BEGIN namespace filesystem { namespace options { namespace concepts {
#endif // __FILESYSTEM_OPTIONS_CONCEPTS_NAMESPACE_BEGIN

#ifndef __FILESYSTEM_OPTIONS_CONCEPTS_NAMESPACE_END
#define __FILESYSTEM_OPTIONS_CONCEPTS_NAMESPACE_END }}}
#endif // __FILESYSTEM_OPTIONS_CONCEPTS_NAMESPACE_END	



#ifndef __FILESYSTEM_IO_NAMESPACE_BEGIN
#define __FILESYSTEM_IO_NAMESPACE_BEGIN namespace filesystem { namespace io {
#endif // __FILESYSTEM_IO_NAMESPACE_BEGIN

#ifndef __FILESYSTEM_IO_NAMESPACE_END
#define __FILESYSTEM_IO_NAMESPACE_END }}
#endif // __FILESYSTEM_IO_NAMESPACE_END



#ifndef __FILESYSTEM_TCP_NAMESPACE_BEGIN
#define __FILESYSTEM_TCP_NAMESPACE_BEGIN namespace filesystem { namespace tcp {
#endif // __FILESYSTEM_TCP_NAMESPACE_BEGIN

#ifndef __FILESYSTEM_TCP_NAMESPACE_END
#define __FILESYSTEM_TCP_NAMESPACE_END }}
#endif // __FILESYSTEM_TCP_NAMESPACE_END	



#ifndef __FILESYSTEM_UDP_NAMESPACE_BEGIN
#define __FILESYSTEM_UDP_NAMESPACE_BEGIN namespace filesystem { namespace udp {
#endif // __FILESYSTEM_UDP_NAMESPACE_BEGIN

#ifndef __FILESYSTEM_UDP_NAMESPACE_END
#define __FILESYSTEM_UDP_NAMESPACE_END }}
#endif // __FILESYSTEM_UDP_NAMESPACE_END
