#pragma once 


#ifndef __FILESYSTEM_NAMESPACE_BEGIN
#define __FILESYSTEM_NAMESPACE_BEGIN namespace fs {
#endif // __FILESYSTEM_NAMESPACE_BEGIN

#ifndef __FILESYSTEM_NAMESPACE_END
#define __FILESYSTEM_NAMESPACE_END }
#endif // __FILESYSTEM_NAMESPACE_END



#ifndef __FILESYSTEM_OPTIONS_NAMESPACE_BEGIN
#define __FILESYSTEM_OPTIONS_NAMESPACE_BEGIN namespace fs { namespace options {
#endif // __FILESYSTEM_OPTIONS_NAMESPACE_BEGIN

#ifndef __FILESYSTEM_OPTIONS_NAMESPACE_END
#define __FILESYSTEM_OPTIONS_NAMESPACE_END }}
#endif // __FILESYSTEM_OPTIONS_NAMESPACE_END



#ifndef __FILESYSTEM_OPTIONS_CONCEPTS_NAMESPACE_BEGIN
#define __FILESYSTEM_OPTIONS_CONCEPTS_NAMESPACE_BEGIN namespace fs { namespace options { namespace concepts {
#endif // __FILESYSTEM_OPTIONS_CONCEPTS_NAMESPACE_BEGIN

#ifndef __FILESYSTEM_OPTIONS_CONCEPTS_NAMESPACE_END
#define __FILESYSTEM_OPTIONS_CONCEPTS_NAMESPACE_END }}}
#endif // __FILESYSTEM_OPTIONS_CONCEPTS_NAMESPACE_END	



#ifndef __FILESYSTEM_IO_NAMESPACE_BEGIN
#define __FILESYSTEM_IO_NAMESPACE_BEGIN namespace fs { namespace io {
#endif // __FILESYSTEM_IO_NAMESPACE_BEGIN

#ifndef __FILESYSTEM_IO_NAMESPACE_END
#define __FILESYSTEM_IO_NAMESPACE_END }}
#endif // __FILESYSTEM_IO_NAMESPACE_END
